# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/repo/scratch/MomentPlus/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/repo/scratch/MomentPlus

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/repo/scratch/MomentPlus/CMakeFiles /root/repo/scratch/MomentPlus/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/repo/scratch/MomentPlus/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MomentPlus_static

# Build rule for target.
MomentPlus_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MomentPlus_static
.PHONY : MomentPlus_static

# fast build rule for target.
MomentPlus_static/fast:
	$(MAKE) -f CMakeFiles/MomentPlus_static.dir/build.make CMakeFiles/MomentPlus_static.dir/build
.PHONY : MomentPlus_static/fast

#=============================================================================
# Target rules for targets named MomentPlus

# Build rule for target.
MomentPlus: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MomentPlus
.PHONY : MomentPlus

# fast build rule for target.
MomentPlus/fast:
	$(MAKE) -f CMakeFiles/MomentPlus.dir/build.make CMakeFiles/MomentPlus.dir/build
.PHONY : MomentPlus/fast

# target to build an object file
date.o:
	$(MAKE) -f CMakeFiles/MomentPlus_static.dir/build.make CMakeFiles/MomentPlus_static.dir/date.o
	$(MAKE) -f CMakeFiles/MomentPlus.dir/build.make CMakeFiles/MomentPlus.dir/date.o
.PHONY : date.o

# target to preprocess a source file
date.i:
	$(MAKE) -f CMakeFiles/MomentPlus_static.dir/build.make CMakeFiles/MomentPlus_static.dir/date.i
	$(MAKE) -f CMakeFiles/MomentPlus.dir/build.make CMakeFiles/MomentPlus.dir/date.i
.PHONY : date.i

# target to generate assembly for a file
date.s:
	$(MAKE) -f CMakeFiles/MomentPlus_static.dir/build.make CMakeFiles/MomentPlus_static.dir/date.s
	$(MAKE) -f CMakeFiles/MomentPlus.dir/build.make CMakeFiles/MomentPlus.dir/date.s
.PHONY : date.s

# target to build an object file
datestuff.o:
	$(MAKE) -f CMakeFiles/MomentPlus_static.dir/build.make CMakeFiles/MomentPlus_static.dir/datestuff.o
	$(MAKE) -f CMakeFiles/MomentPlus.dir/build.make CMakeFiles/MomentPlus.dir/datestuff.o
.PHONY : datestuff.o

# target to preprocess a source file
datestuff.i:
	$(MAKE) -f CMakeFiles/MomentPlus_static.dir/build.make CMakeFiles/MomentPlus_static.dir/datestuff.i
	$(MAKE) -f CMakeFiles/MomentPlus.dir/build.make CMakeFiles/MomentPlus.dir/datestuff.i
.PHONY : datestuff.i

# target to generate assembly for a file
datestuff.s:
	$(MAKE) -f CMakeFiles/MomentPlus_static.dir/build.make CMakeFiles/MomentPlus_static.dir/datestuff.s
	$(MAKE) -f CMakeFiles/MomentPlus.dir/build.make CMakeFiles/MomentPlus.dir/datestuff.s
.PHONY : datestuff.s

# target to build an object file
fulldate.o:
	$(MAKE) -f CMakeFiles/MomentPlus_static.dir/build.make CMakeFiles/MomentPlus_static.dir/fulldate.o
	$(MAKE) -f CMakeFiles/MomentPlus.dir/build.make CMakeFiles/MomentPlus.dir/fulldate.o
.PHONY : fulldate.o

# target to preprocess a source file
fulldate.i:
	$(MAKE) -f CMakeFiles/MomentPlus_static.dir/build.make CMakeFiles/MomentPlus_static.dir/fulldate.i
	$(MAKE) -f CMakeFiles/MomentPlus.dir/build.make CMakeFiles/MomentPlus.dir/fulldate.i
.PHONY : fulldate.i

# target to generate assembly for a file
fulldate.s:
	$(MAKE) -f CMakeFiles/MomentPlus_static.dir/build.make CMakeFiles/MomentPlus_static.dir/fulldate.s
	$(MAKE) -f CMakeFiles/MomentPlus.dir/build.make CMakeFiles/MomentPlus.dir/fulldate.s
.PHONY : fulldate.s

# target to build an object file
year.o:
	$(MAKE) -f CMakeFiles/MomentPlus_static.dir/build.make CMakeFiles/MomentPlus_static.dir/year.o
	$(MAKE) -f CMakeFiles/MomentPlus.dir/build.make CMakeFiles/MomentPlus.dir/year.o
.PHONY : year.o

# target to preprocess a source file
year.i:
	$(MAKE) -f CMakeFiles/MomentPlus_static.dir/build.make CMakeFiles/MomentPlus_static.dir/year.i
	$(MAKE) -f CMakeFiles/MomentPlus.dir/build.make CMakeFiles/MomentPlus.dir/year.i
.PHONY : year.i

# target to generate assembly for a file
year.s:
	$(MAKE) -f CMakeFiles/MomentPlus_static.dir/build.make CMakeFiles/MomentPlus_static.dir/year.s
	$(MAKE) -f CMakeFiles/MomentPlus.dir/build.make CMakeFiles/MomentPlus.dir/year.s
.PHONY : year.s

# target to build an object file
ymonth.o:
	$(MAKE) -f CMakeFiles/MomentPlus_static.dir/build.make CMakeFiles/MomentPlus_static.dir/ymonth.o
	$(MAKE) -f CMakeFiles/MomentPlus.dir/build.make CMakeFiles/MomentPlus.dir/ymonth.o
.PHONY : ymonth.o

# target to preprocess a source file
ymonth.i:
	$(MAKE) -f CMakeFiles/MomentPlus_static.dir/build.make CMakeFiles/MomentPlus_static.dir/ymonth.i
	$(MAKE) -f CMakeFiles/MomentPlus.dir/build.make CMakeFiles/MomentPlus.dir/ymonth.i
.PHONY : ymonth.i

# target to generate assembly for a file
ymonth.s:
	$(MAKE) -f CMakeFiles/MomentPlus_static.dir/build.make CMakeFiles/MomentPlus_static.dir/ymonth.s
	$(MAKE) -f CMakeFiles/MomentPlus.dir/build.make CMakeFiles/MomentPlus.dir/ymonth.s
.PHONY : ymonth.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... MomentPlus_static"
	@echo "... rebuild_cache"
	@echo "... MomentPlus"
	@echo "... date.o"
	@echo "... date.i"
	@echo "... date.s"
	@echo "... datestuff.o"
	@echo "... datestuff.i"
	@echo "... datestuff.s"
	@echo "... fulldate.o"
	@echo "... fulldate.i"
	@echo "... fulldate.s"
	@echo "... year.o"
	@echo "... year.i"
	@echo "... year.s"
	@echo "... ymonth.o"
	@echo "... ymonth.i"
	@echo "... ymonth.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

